// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsRelationship.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsRelationship.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829164039_SnakeCaseNaming")]
    partial class SnakeCaseNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.CbDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cb_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cb_departments_name");

                    b.ToTable("cb_departments", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.ColumbusUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EntraObjectId")
                        .HasColumnType("text")
                        .HasColumnName("entra_object_id");

                    b.Property<DateTimeOffset?>("LastSurveyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_survey_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_columbus_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_columbus_users_email");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_columbus_users_entra_object_id")
                        .HasFilter("entra_object_id IS NOT NULL");

                    b.ToTable("columbus_users", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_ms_domains");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_domains_name");

                    b.ToTable("ms_domains", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ms_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_groups_name");

                    b.ToTable("ms_groups", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ms_sources");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_sources_name");

                    b.ToTable("ms_sources", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
