// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsRelationship.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsRelationship.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915215252_RelationHistory")]
    partial class RelationHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.CbDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_cb_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cb_departments_name");

                    b.ToTable("cb_departments", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.ColumbusUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_columbus_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_columbus_users_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_columbus_users_email");

                    b.ToTable("columbus_users", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<string>("UpdatedLabel")
                        .HasColumnType("text")
                        .HasColumnName("updated_label");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dashboards");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboards_slug");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("DashboardId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_domains_dashboard_id_name");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_ms_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_groups_name");

                    b.ToTable("ms_groups", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_key");

                    b.Property<bool>("IsTentative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tentative");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ms_profiles");

                    b.HasIndex("IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_profiles_identity_key");

                    b.ToTable("ms_profiles", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsProfileCustomer", b =>
                {
                    b.Property<Guid>("MsProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ms_profile_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.HasKey("MsProfileId", "CustomerId")
                        .HasName("pk_ms_profile_customers");

                    b.ToTable("ms_profile_customers", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsProfileDomain", b =>
                {
                    b.Property<Guid>("MsProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ms_profile_id");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.HasKey("MsProfileId", "DomainId")
                        .HasName("pk_ms_profile_domains");

                    b.ToTable("ms_profile_domains", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.MsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_ms_sources");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ms_sources_name");

                    b.ToTable("ms_sources", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColumbusUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("columbus_user_id");

                    b.Property<Guid>("MsProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ms_profile_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_relations");

                    b.HasIndex("ColumbusUserId", "MsProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_relations_columbus_user_id_ms_profile_id");

                    b.ToTable("relations", null, t =>
                        {
                            t.HasCheckConstraint("ck_relations_score_range", "score BETWEEN -3 AND 3");
                        });
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.RelationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("ColumbusUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("columbus_user_id");

                    b.Property<Guid>("MsProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ms_profile_id");

                    b.Property<string>("NewNote")
                        .HasColumnType("text")
                        .HasColumnName("new_note");

                    b.Property<short?>("NewScore")
                        .HasColumnType("smallint")
                        .HasColumnName("new_score");

                    b.Property<string>("OldNote")
                        .HasColumnType("text")
                        .HasColumnName("old_note");

                    b.Property<short?>("OldScore")
                        .HasColumnType("smallint")
                        .HasColumnName("old_score");

                    b.HasKey("Id")
                        .HasName("pk_relation_history");

                    b.ToTable("relation_history", (string)null);
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.ColumbusUser", b =>
                {
                    b.HasOne("MsRelationship.Api.Data.Entities.CbDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_columbus_users_cb_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MsRelationship.Api.Data.Entities.Domain", b =>
                {
                    b.HasOne("MsRelationship.Api.Data.Entities.Dashboard", "Dashboard")
                        .WithMany()
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_domains_dashboards_dashboard_id");

                    b.Navigation("Dashboard");
                });
#pragma warning restore 612, 618
        }
    }
}
