-- The mockup's data. Run by hand into an empty database:
--   docker compose exec -T db psql -U app -d app -v ON_ERROR_STOP=1 < db/seed.sql
-- Generated once from the root index.html (the mockup). The Columbus users,
-- every score and every note are placeholders.

begin;

insert into boards (id, label, dashboard, graphics, subtitle, updated, version, owner, system) values
  ('data-ai', 'Data & AI', 'dashboard', 'graphic-view', 'Who we know at Microsoft Denmark, and how well', 'August 2026', 'v0.3 draft', 'owner not yet assigned', true),
  ('dynamics', 'Dynamics', 'dashboard-dynamics', 'graphic-view-dynamics', 'Who we know in Microsoft’s Business Applications organisation', 'May 2026', 'v0.1 draft', 'owner not yet assigned', false);

insert into domains (id, dept, name, owner, "desc", panel) values
  ('d1', 'data-ai', 'Azure & AI - Sales', 'Mette Kirkegaard', 'Cloud & AI platform sales, Azure and Data & AI sales specialists.', '{"title":"Azure & AI","subtitle":"Sales","accent":"violet","icon":"trending-up","layout":"grid-2","position":"left-1","connect":true,"max":null}'::jsonb),
  ('d2', 'data-ai', 'Strategic & Partner Leadership', 'Mette Kirkegaard', 'Enterprise partner solutions and partner development - our formal route in.', '{"title":"Strategic & Partner Leadership","subtitle":null,"accent":"blue","icon":"lightbulb","layout":"rows","position":"centre-top","connect":true,"max":null}'::jsonb),
  ('d3', 'data-ai', 'Azure & AI - Specialist', 'Jonas Ravn', 'Cloud solution architects, AI solution engineers and Azure specialists.', '{"title":"Azure & AI","subtitle":"Specialist","accent":"green","icon":"briefcase","layout":"grid-2","position":"right-1","connect":true,"max":null}'::jsonb),
  ('d4', 'data-ai', 'Business Applications', 'Sofie Bang', 'Dynamics 365, Power Platform and Copilot motions.', '{"title":"Business Applications","subtitle":"Dynamics 365, Power Platform & Copilot","accent":"rose","icon":"building","layout":"grid-2","position":"left-2","connect":true,"max":null}'::jsonb),
  ('d5', 'data-ai', 'SMC & SMB', 'Anders Holmgaard', 'Small, medium and corporate segment across DK / NO.', '{"title":"SMC & SMB","subtitle":"Small, medium & corporate segment","accent":"teal","icon":"users","layout":"rows","position":"right-2","connect":true,"max":null}'::jsonb),
  ('d6', 'data-ai', 'Fabric Partner Success', 'Rikke Dalsgaard', 'Microsoft Fabric partner ecosystem and joint success motions.', '{"title":"Fabric Partner Success","subtitle":null,"accent":"orange","icon":"layers","layout":"rows","position":"centre-bottom","connect":true,"max":null}'::jsonb),
  ('d7', 'data-ai', 'Funding & Programs', 'Sofie Bang', 'Co-sell, incentives, MCI and Azure Accelerate deployment funding.', '{"title":"Funding & Programs","subtitle":null,"accent":"amber","icon":"gift","layout":"bare","position":"bottom-1","connect":false,"max":null}'::jsonb),
  ('d8', 'data-ai', 'Wider network', 'Jonas Ravn', 'Contacts we hold but have not yet placed against a domain.', '{"title":"Wider network","subtitle":"placement to be decided","accent":"slate","icon":"globe","layout":"bare","position":"bottom-2","connect":false,"max":null}'::jsonb),
  ('dy1', 'dynamics', 'BizApp STU Leadership', 'Thomas Johansson', 'Solution Tech Unit leads for Business Applications - Enterprise, SME-C and SMB.', '{"title":"BizApp STU Leadership","subtitle":null,"accent":"blue","icon":"lightbulb","layout":"rows","position":"centre-top","connect":true,"max":3}'::jsonb),
  ('dy2', 'dynamics', 'Enterprise BizApp Sellers', 'Carsten Møberg', 'Solution Sales Professionals on Dynamics 365 and Power Platform, enterprise accounts.', '{"title":"Enterprise BizApp Sellers","subtitle":"Dynamics 365 & Power Platform","accent":"rose","icon":"building","layout":"grid-2","position":"left-1","connect":true,"max":4}'::jsonb),
  ('dy3', 'dynamics', 'SME-C BizApp', 'Carsten Møberg', 'AI Business Solutions sellers in the SME-C segment, DK / NO / Iceland.', '{"title":"SME-C BizApp","subtitle":"DK, NO & Iceland","accent":"teal","icon":"users","layout":"grid-2","position":"right-1","connect":true,"max":4}'::jsonb),
  ('dy4', 'dynamics', 'SMB', 'Thomas Johansson', 'Small and medium business segment - roughly a thousand customers behind one seller.', '{"title":"SMB","subtitle":"~1.000 customers","accent":"amber","icon":"globe","layout":"bare","position":"bottom-1","connect":false,"max":null}'::jsonb),
  ('dy5', 'dynamics', 'Technical Specialists', 'John Sinnbeck', 'TSPs behind the BizApp sellers. Named in the deck, nobody scored yet.', '{"title":"Technical Specialists","subtitle":null,"accent":"orange","icon":"wrench","layout":"rows","position":"centre-bottom","connect":true,"max":3}'::jsonb),
  ('dy6', 'dynamics', 'Microsoft DK Leadership', 'Thomas Johansson', 'Country leadership. Shared with the Data & AI board - the same people, one score.', '{"title":"Microsoft DK Leadership","subtitle":"shared with Data & AI","accent":"violet","icon":"crown","layout":"grid-2","position":"left-2","connect":true,"max":4}'::jsonb),
  ('dy7', 'dynamics', 'Partner & Alliance', 'Thomas Johansson', 'Partner development and alliance roles. Shared with the Data & AI board.', '{"title":"Partner & Alliance","subtitle":"shared with Data & AI","accent":"slate","icon":"link","layout":"bare","position":"bottom-2","connect":false,"max":4}'::jsonb),
  ('dy8', 'dynamics', 'ATU Industry Sales', 'Anders Barslund', 'Account teams per industry - manufacturing, retail, OCI. They sell everything, Dynamics included.', '{"title":"ATU Industry Sales","subtitle":"account teams per industry","accent":"green","icon":"briefcase","layout":"grid-2","position":"right-2","connect":true,"max":4}'::jsonb);

insert into customers (id, name, type) values
  ('cu1', 'AMBU A/S', 'unknown'),
  ('cu2', 'Interactive Sports Games A/S', 'unknown'),
  ('cu3', 'Topsøe A/S', 'unknown'),
  ('cu4', 'VELUX A/S', 'unknown'),
  ('cu5', 'Viking Lifesavings', 'unknown'),
  ('cu6', 'Energinet', 'unknown'),
  ('cu7', 'Netcompany', 'unknown'),
  ('cu8', 'Air Greenland', 'unknown'),
  ('cu9', 'Royal Greenland', 'unknown'),
  ('cu10', 'Tele Greenland', 'unknown'),
  ('cu11', 'Grønlands Selvstyre', 'unknown'),
  ('cu12', 'Arla Foods Amba', 'unknown'),
  ('cu13', 'Bestseller A/S', 'unknown'),
  ('cu14', 'Danish Agro', 'unknown'),
  ('cu15', 'Danish Crown Amba', 'unknown'),
  ('cu16', 'ECCO SKO A/S', 'unknown'),
  ('cu17', 'Danfoss A/S', 'unknown'),
  ('cu18', 'Jysk A/S', 'unknown'),
  ('cu19', 'Salling Group A/S', 'unknown'),
  ('cu20', 'GRUNDFOS DK', 'unknown'),
  ('cu21', 'Hempel A/S', 'unknown'),
  ('cu22', 'Alm Brand Af 1792', 'unknown'),
  ('cu23', 'Ap Pension A/S', 'unknown'),
  ('cu24', 'Danske Bank Group', 'unknown'),
  ('cu25', 'JN Data', 'unknown'),
  ('cu26', 'Nordea A/S', 'unknown'),
  ('cu27', 'Pensiondanmark', 'unknown'),
  ('cu28', 'PFA Pension', 'unknown'),
  ('cu29', 'Saxo Bank A/S', 'unknown'),
  ('cu30', 'SDC A/S', 'unknown'),
  ('cu31', 'Tryg', 'unknown'),
  ('cu32', 'NOVO NORDISK', 'unknown'),
  ('cu33', 'Vestas Wind Systems', 'unknown'),
  ('cu34', 'Andel a.m.b.a.', 'unknown'),
  ('cu35', 'Blue Water Shipping A/S', 'unknown'),
  ('cu36', 'DSV A/S', 'unknown'),
  ('cu37', 'Flsmidth & Co A/S', 'unknown'),
  ('cu38', 'GN Store Nord A/S', 'unknown'),
  ('cu39', 'Københavns Lufthavne A/S', 'unknown'),
  ('cu40', 'LEGO GROUP', 'unknown'),
  ('cu41', 'Norlys', 'unknown'),
  ('cu42', 'Orsted A/S', 'unknown'),
  ('cu43', 'A.P. Møller – Maersk Group', 'unknown'),
  ('cu44', 'COOP DANMARK A/S', 'unknown'),
  ('cu45', 'DFDS A/S', 'unknown'),
  ('cu46', 'Egmont', 'unknown'),
  ('cu47', 'ISS A/S', 'unknown'),
  ('cu48', 'Kamstrup Energi A/S', 'unknown'),
  ('cu49', 'NILFISK-ADVANCE A/S', 'unknown'),
  ('cu50', 'Pandora Holding A/S', 'unknown'),
  ('cu51', 'Ramboll Gruppen A/S', 'unknown'),
  ('cu52', 'Semler Gruppen A/S', 'unknown'),
  ('cu53', 'Stark Group A/S', 'unknown'),
  ('cu54', 'Coloplast A/S', 'unknown'),
  ('cu55', 'Genmab A/S', 'unknown'),
  ('cu56', 'H. Lundbeck A/S', 'unknown'),
  ('cu57', 'LEO Pharma A/S', 'unknown'),
  ('cu58', 'Novonesis Group', 'unknown'),
  ('cu59', 'OTICON A/S', 'unknown'),
  ('cu60', 'Cowi A/S', 'unknown'),
  ('cu61', 'Falck A/S', 'unknown'),
  ('cu62', 'PER AARSLEFF A/S', 'unknown'),
  ('cu63', 'TDC A/S', 'unknown'),
  ('cu64', 'Aktieselskabet Schouw & Co.', 'unknown'),
  ('cu65', 'Bang & Olufsen A/S', 'unknown'),
  ('cu66', 'NKT Holding A/S', 'unknown'),
  ('cu67', 'Rockwool International', 'unknown'),
  ('cu68', 'Scandinavian Tobacco Group', 'unknown'),
  ('cu69', 'Carlsberg Group', 'unknown'),
  ('cu70', 'Ferring Pharmaceuticals A/S', 'unknown');

insert into columbus_profiles (id, name, title, department, skills, role, email, phone, from_deck) values
  ('c1', 'Mette Kirkegaard', 'Partner Alliance Manager', 'Alliances', array['Alliances', 'Co-sell', 'Governance']::text[], 'admin', 'mette.kirkegaard@columbusglobal.example', '', false),
  ('c2', 'Jesper Winther', 'Managing Director, Denmark', 'Executive', array['Strategy', 'Executive sponsor']::text[], 'superadmin', 'jesper.winther@columbusglobal.example', '', false),
  ('c3', 'Sofie Bang', 'Business Applications Director', 'Business Applications', array['D365 F&O', 'ERP', 'Presales']::text[], 'admin', 'sofie.bang@columbusglobal.example', '', false),
  ('c4', 'Jonas Ravn', 'Cloud Practice Lead', 'Cloud & Infrastructure', array['Azure', 'Migration', 'Architecture']::text[], 'moderator', 'jonas.ravn@columbusglobal.example', '', false),
  ('c5', 'Rikke Dalsgaard', 'Security Lead', 'Cloud & Infrastructure', array['Security', 'Entra', 'Compliance']::text[], 'moderator', 'rikke.dalsgaard@columbusglobal.example', '', false),
  ('c6', 'Anders Holmgaard', 'Modern Work Consultant', 'Modern Work', array['M365', 'Teams', 'Adoption']::text[], 'standard', 'anders.holmgaard@columbusglobal.example', '', false),
  ('c7', 'Line Aagaard', 'Data & AI Consultant', 'Data & AI', array['Fabric', 'Power BI', 'Data platform']::text[], 'standard', 'line.aagaard@columbusglobal.example', '', false),
  ('c8', 'Peter Sandholm', 'Enterprise Account Manager', 'Sales', array['Sales', 'Public sector']::text[], 'standard', 'peter.sandholm@columbusglobal.example', '', false),
  ('c9', 'Amalie Friis', 'Marketing Manager', 'Marketing', array['Campaigns', 'Events']::text[], 'standard', 'amalie.friis@columbusglobal.example', '', false),
  ('c10', 'Christian Bloch', 'Solution Architect', 'Cloud & Infrastructure', array['Azure', 'Landing zones']::text[], 'standard', 'christian.bloch@columbusglobal.example', '', false),
  ('c11', 'Louise Damgaard', 'D365 CE Consultant', 'Business Applications', array['D365 CE', 'Power Platform']::text[], 'standard', 'louise.damgaard@columbusglobal.example', '', false),
  ('c12', 'Martin Østergaard', 'Delivery Manager', 'Delivery', array['Delivery', 'PMO']::text[], 'standard', 'martin.oestergaard@columbusglobal.example', '', false),
  ('c13', 'Sara Lykke', 'Presales Lead, Data & AI', 'Data & AI', array['Presales', 'AI', 'Copilot']::text[], 'standard', 'sara.lykke@columbusglobal.example', '', false),
  ('c14', 'Daniel Hvid', 'Bid Manager', 'Sales', array['Bids', 'Public tenders']::text[], 'standard', 'daniel.hvid@columbusglobal.example', '', false),
  ('c15', 'Thomas Johansson', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c16', 'Anders Barslund', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c17', 'Anders Skibild', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c18', 'Brian B. Jørgensen', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c19', 'Carsten Møberg', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c20', 'Christian Poppe', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c21', 'John Sinnbeck', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c22', 'Stig B. Madsen', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c23', 'Søren Krogh', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c24', 'Lars Verning', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c25', 'Niels Viskum', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true),
  ('c26', 'Frederik Jørgensen', 'Microsoft relationship owner', 'Business Applications', '{}'::text[], 'standard', '', '', true);

insert into ms_profiles (id, name, title, "group", source, email, phone, notes, tentative, cadence, updated_at) values
  ('m1', 'Nina Due', 'Director, Enterprise Partner Solutions', 'Leadership', 'Microsoft DK leadership page', '', '', 'Listed on the Microsoft DK leadership page.', false, 'monthly', '2026-08-19'),
  ('m2', 'Christian Koch-Bentzen', 'Sr. Partner Development Manager', 'Partner Development', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m3', 'Claus Iversen', 'Partner Solution Sales Manager, Cloud & AI Platform / Azure', 'Partner Development', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m4', 'Kris Rozanka', 'Cloud & AI Sales Consultant', 'Account Team', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m5', 'Arthur Gentit', 'Sales Specialist, Data & AI', 'Account Team', 'Ayla''s list', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m6', 'Aybike Bozkurt', 'Azure Cloud Solution Sales Executive', 'Account Team', 'Ayla''s list', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m7', 'Mauro Dalvit', 'AI Solution Engineer', 'Technical Specialist', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m8', 'Nikhil Makkar', 'Senior Cloud Solutions Architect', 'Technical Specialist', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m9', 'Chandana Ramesh', 'Cloud Solution Architect', 'Technical Specialist', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m10', 'Marcus Quistgaard', 'Azure Specialist', 'Technical Specialist', 'Ayla''s list', '', '', '', false, 'none', '2026-08-19'),
  ('m11', 'Bo Kaaber Brandt', 'GTM Lead, Dynamics 365 & Power Platform', 'Leadership', 'LinkedIn / MS Pulse', '', '', '', false, 'monthly', '2026-08-19'),
  ('m12', 'Anders Fjordhøj', 'Sr. Technical Specialist, Power Platform & AI', 'Technical Specialist', 'LinkedIn / MS Pulse', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m13', 'Jesper N. Pedersen', 'Solution Sales Professional, BizApps', 'Account Team', 'LinkedIn / MS Pulse', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m14', 'Bo Larsen', 'Solution Sales Professional, BizApps', 'Account Team', 'Unconfirmed', '', '', 'Role and placement still to be confirmed.', true, 'quarterly', '2026-08-19'),
  ('m15', 'Sarah McKenna', 'SMC & SMB Lead, DK / NO', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-08-19'),
  ('m16', 'Thomas Lundgren', 'SMC Azure Lead', 'Leadership', 'Ayla''s list', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m17', 'Kasper N. Nielsen', 'Senior Sales Executive, Aalborg', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m18', 'Prashant Gutala', 'Fabric Partner Ecosystem Lead', 'Partner Development', 'Ayla''s list', '', '', '', false, 'monthly', '2026-08-19'),
  ('m19', 'Mads Hammerbak', 'Funding & programs', 'Partner Development', 'Ayla''s list', '', '', '', false, 'quarterly', '2026-08-19'),
  ('m20', 'Azure Accelerate Team', 'Deployment funding, guidance', 'Partner Development', 'Ayla''s list', '', '', 'A Microsoft team, not a single named contact.', false, 'none', '2026-08-19'),
  ('m21', 'Frederikke Smidt', 'Sr. Customer Success Account Mgr', 'Account Team', 'Ayla''s list', '', '', 'Domain placement still to be decided.', false, 'none', '2026-08-19'),
  ('m22', 'Malte Vilain', 'Account Executive', 'Account Team', 'Ayla''s list', '', '', 'Domain placement still to be decided.', false, 'none', '2026-08-19'),
  ('m23', 'Lars-Bo Heidemann', 'Cyber Security Professional', 'Technical Specialist', 'Ayla''s list', '', '', 'Domain placement still to be decided.', false, 'quarterly', '2026-08-19'),
  ('dm1', 'Abed Danial', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm2', 'Ana-Maria Cibotari', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm3', 'Anders Andersen', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm4', 'Anders Helmo Larsen', 'Sr Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm5', 'Artur Bagrancev', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm6', 'Bashar Shahmorad', 'SME-C sales', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm7', 'Bo Brandt', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', 'Possibly the same person as Bo Kaaber Brandt - the deck lists them separately.', true, 'monthly', '2026-05-27'),
  ('dm8', 'Brian Guldborg', 'STU Lead, Solution TechUnit', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm9', 'Brian Laustsen', 'Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm10', 'Camilla Anker Schösser', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm11', 'Charlotte Burmeister', 'Sales Manger (ATU) - Manufacturing', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm12', 'Christian Schønau', 'Sr Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm13', 'Dann Andersen', 'Sr Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm14', 'Darren Murphy', 'Sr Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm15', 'Esben Holtum', 'Sr Account Tech Strategist, Major', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm16', 'Fillip Knudsen', 'Sr Strategic Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm17', 'Helle Huss', 'Commercial Lead EOU', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm18', 'Henrik Ditlevsen', 'Ent. Sales', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm19', 'Jacob Louis Vagn Jensen', 'Sales Manager (ATU Retail and Professional services)', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm20', 'Jakub Federowicz', 'Account Executive Intern', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm21', 'Jan Akselbo', 'SME-C Sales', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm22', 'Jan Christensen', 'Sr. Technical Specialsit', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm23', 'Jannic Jensen', 'Account Technology Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm24', 'Jens Fjeldal', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm25', 'Jens Kofod', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm26', 'Jens Østvang', 'SME-C sales', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm27', 'Jeppe Skovhus Gerholt', 'COO', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm28', 'Jeshri', 'AI Biz SSP, SME-C', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', 'Microsoft alias from the deck; full name not resolved.', true, 'monthly', '2026-05-27'),
  ('dm29', 'Jesper Nielsen', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm30', 'Jette Nedergaard Madsen', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm31', 'Johan Grene', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm32', 'Jon Edmonds', 'Director, Strategic Sales - Mærsk', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm33', 'Jonas Rolsted', 'Sr Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm34', 'Jonathan Sørensen', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm35', 'Juliane Maack', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', 'Listed both as a TSP and as an SME-C AI Biz SSP - placement to confirm.', true, 'none', '2026-05-27'),
  ('dm36', 'Julie Aabo', 'Strategic Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm37', 'Julie Nadelmann', 'Global partner solution director', 'Partner Development', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm38', 'Kasper Vedel Mørch', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm39', 'Katarina Larsson', 'EMEA marketing GTM Lead Bizzapps', 'Marketing', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm40', 'Katherina Hansen', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm41', 'Kristian Albertsen', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm42', 'Kristoffer Rosenmeier', 'Ent. STU/ Sales lead - Security', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm43', 'Lene Stone', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm44', 'Liang Ye', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm45', 'Line Sinding Skøtt', 'PS Lead', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm46', 'Liv Tornquist', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm47', 'Louise Elsberg', 'Manufacturing Industry Lead', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm48', 'Lukkas Hamann', 'Strategic Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm49', 'Lynn Friedland', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm50', 'Mads Kjærsgaard', 'Sr Sales Manager (ATU) - FSI', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm51', 'Malou Reedorf', 'AE', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm52', 'Marc Solling', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm53', 'Maria Moeslund Hansen', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm54', 'Matilda Varvne', 'Account Executive, Major', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm55', 'Mette Louise Kaagaard', 'GM DK', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm56', 'Mette Nygaard Ørnbo', 'Account Tech Strategist, Major', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm57', 'Mia dong', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm58', 'Michael Olsson', 'Sr Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm59', 'Mikkel Schausen', 'SSP BizApp', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'monthly', '2026-05-27'),
  ('dm60', 'Morten Kvist Thomsen', 'CSU Lead', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm61', 'Nicolas Richardot', 'Sr Strategic Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm62', 'Niels Grønning', 'Ent. STU/ Sales lead - Data/AI', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm63', 'Pepijn van den Brink', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm64', 'Peter Basbøll', 'Sr Strategic Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm65', 'Peter Lippert', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm66', 'Poul Jørgensen', 'Sales Manager AI business solutions', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm67', 'Rasmus Knudsen', 'Account Executive, Major', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm68', 'Sarah McGeller', 'STU Lead, SME-C BizApp', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', 'Possibly the same person as Sarah McKenna - to confirm.', true, 'none', '2026-05-27'),
  ('dm69', 'Sigrid Wallin', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm70', 'Simon Bolther', 'TSM AI BizApp', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', 'The deck writes Ørsted beside his name - that is his account, not part of his title.', false, 'quarterly', '2026-05-27'),
  ('dm71', 'Siri Venning', 'TSP', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'none', '2026-05-27'),
  ('dm72', 'Tanya Helene Christensen', 'SSM AI BizApp', 'Leadership', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm73', 'Thomas Christensen', 'Account Tech Strategist', 'Technical Specialist', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm74', 'Thomas Redder', 'STU SSP, AI BizApp Denmark', 'Technical Specialist', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm75', 'Tim Holbek', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27'),
  ('dm76', 'Tine Haaber', 'Sr Sales Manager – OCI (pharma, energy, other industries)', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm77', 'Trine Lumby', 'Ent. Sales', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm78', 'Uche Ojimadu', 'SME-C Sales Account manager AI business', 'Account Team', 'LinkedIn / Thomas'' deck', '', '', '', false, 'quarterly', '2026-05-27'),
  ('dm79', 'Zenia Harpsoe', 'Account Executive', 'Account Team', 'Microsoft DK org chart', '', '', '', false, 'none', '2026-05-27');

insert into profile_domains (ms_profile_id, domain_id) values
  ('m1', 'd2'),
  ('m1', 'dy7'),
  ('m2', 'd2'),
  ('m2', 'dy7'),
  ('m3', 'd1'),
  ('m4', 'd1'),
  ('m5', 'd1'),
  ('m6', 'd1'),
  ('m7', 'd3'),
  ('m8', 'd3'),
  ('m9', 'd3'),
  ('m10', 'd3'),
  ('m11', 'd4'),
  ('m11', 'dy2'),
  ('m12', 'd4'),
  ('m13', 'd4'),
  ('m13', 'dy2'),
  ('m14', 'd4'),
  ('m14', 'dy2'),
  ('m15', 'd5'),
  ('m15', 'dy4'),
  ('m16', 'd5'),
  ('m17', 'd5'),
  ('m18', 'd6'),
  ('m19', 'd7'),
  ('m20', 'd7'),
  ('m21', 'd8'),
  ('m22', 'd8'),
  ('m23', 'd8'),
  ('dm1', 'dy3'),
  ('dm2', 'dy2'),
  ('dm3', 'dy5'),
  ('dm4', 'dy8'),
  ('dm5', 'dy5'),
  ('dm6', 'dy3'),
  ('dm7', 'dy2'),
  ('dm8', 'dy1'),
  ('dm9', 'dy8'),
  ('dm10', 'dy8'),
  ('dm11', 'dy8'),
  ('dm12', 'dy8'),
  ('dm13', 'dy8'),
  ('dm14', 'dy8'),
  ('dm15', 'dy8'),
  ('dm16', 'dy8'),
  ('dm17', 'dy8'),
  ('dm18', 'dy2'),
  ('dm19', 'dy8'),
  ('dm20', 'dy8'),
  ('dm21', 'dy3'),
  ('dm22', 'dy5'),
  ('dm23', 'dy8'),
  ('dm24', 'dy8'),
  ('dm25', 'dy5'),
  ('dm26', 'dy3'),
  ('dm27', 'dy6'),
  ('dm28', 'dy3'),
  ('dm29', 'dy5'),
  ('dm30', 'dy8'),
  ('dm31', 'dy5'),
  ('dm32', 'dy8'),
  ('dm33', 'dy8'),
  ('dm34', 'dy5'),
  ('dm35', 'dy5'),
  ('dm36', 'dy8'),
  ('dm37', 'dy7'),
  ('dm38', 'dy2'),
  ('dm39', 'dy7'),
  ('dm40', 'dy8'),
  ('dm41', 'dy8'),
  ('dm42', 'dy1'),
  ('dm43', 'dy8'),
  ('dm44', 'dy2'),
  ('dm45', 'dy6'),
  ('dm46', 'dy5'),
  ('dm47', 'dy1'),
  ('dm48', 'dy8'),
  ('dm49', 'dy5'),
  ('dm50', 'dy8'),
  ('dm51', 'dy2'),
  ('dm52', 'dy5'),
  ('dm53', 'dy8'),
  ('dm54', 'dy8'),
  ('dm55', 'dy6'),
  ('dm56', 'dy8'),
  ('dm57', 'dy5'),
  ('dm58', 'dy8'),
  ('dm59', 'dy2'),
  ('dm60', 'dy6'),
  ('dm61', 'dy8'),
  ('dm62', 'dy1'),
  ('dm63', 'dy8'),
  ('dm64', 'dy8'),
  ('dm65', 'dy5'),
  ('dm66', 'dy1'),
  ('dm67', 'dy8'),
  ('dm68', 'dy1'),
  ('dm69', 'dy5'),
  ('dm70', 'dy1'),
  ('dm71', 'dy5'),
  ('dm72', 'dy1'),
  ('dm73', 'dy8'),
  ('dm74', 'dy4'),
  ('dm75', 'dy8'),
  ('dm76', 'dy8'),
  ('dm77', 'dy2'),
  ('dm78', 'dy3'),
  ('dm79', 'dy8');

insert into profile_customers (ms_profile_id, customer_id) values
  ('m13', 'cu12'),
  ('m13', 'cu13'),
  ('m13', 'cu14'),
  ('m13', 'cu15'),
  ('m13', 'cu16'),
  ('m13', 'cu17'),
  ('m13', 'cu18'),
  ('m13', 'cu19'),
  ('m13', 'cu20'),
  ('m13', 'cu21'),
  ('m13', 'cu32'),
  ('m13', 'cu33'),
  ('m14', 'cu12'),
  ('m14', 'cu13'),
  ('m14', 'cu14'),
  ('m14', 'cu15'),
  ('m14', 'cu16'),
  ('m14', 'cu17'),
  ('m14', 'cu18'),
  ('m14', 'cu19'),
  ('m14', 'cu20'),
  ('m14', 'cu21'),
  ('dm1', 'cu54'),
  ('dm1', 'cu55'),
  ('dm1', 'cu56'),
  ('dm1', 'cu57'),
  ('dm1', 'cu58'),
  ('dm1', 'cu59'),
  ('dm1', 'cu60'),
  ('dm1', 'cu61'),
  ('dm1', 'cu62'),
  ('dm1', 'cu63'),
  ('dm2', 'cu1'),
  ('dm2', 'cu2'),
  ('dm2', 'cu3'),
  ('dm2', 'cu4'),
  ('dm2', 'cu5'),
  ('dm2', 'cu64'),
  ('dm2', 'cu65'),
  ('dm2', 'cu66'),
  ('dm2', 'cu67'),
  ('dm2', 'cu68'),
  ('dm2', 'cu69'),
  ('dm2', 'cu70'),
  ('dm7', 'cu6'),
  ('dm7', 'cu7'),
  ('dm7', 'cu8'),
  ('dm7', 'cu9'),
  ('dm7', 'cu10'),
  ('dm7', 'cu11'),
  ('dm18', 'cu22'),
  ('dm18', 'cu23'),
  ('dm18', 'cu24'),
  ('dm18', 'cu25'),
  ('dm18', 'cu26'),
  ('dm18', 'cu27'),
  ('dm18', 'cu28'),
  ('dm18', 'cu29'),
  ('dm18', 'cu30'),
  ('dm18', 'cu31'),
  ('dm38', 'cu34'),
  ('dm38', 'cu35'),
  ('dm38', 'cu36'),
  ('dm38', 'cu37'),
  ('dm38', 'cu38'),
  ('dm38', 'cu39'),
  ('dm38', 'cu40'),
  ('dm38', 'cu41'),
  ('dm38', 'cu42'),
  ('dm44', 'cu43'),
  ('dm59', 'cu44'),
  ('dm59', 'cu45'),
  ('dm59', 'cu46'),
  ('dm59', 'cu47'),
  ('dm59', 'cu48'),
  ('dm59', 'cu49'),
  ('dm59', 'cu50'),
  ('dm59', 'cu51'),
  ('dm59', 'cu52'),
  ('dm59', 'cu53');

insert into relations (id, columbus_id, ms_profile_id, score, note, updated_at) values
  ('r1', 'c1', 'm1', 3, 'Alliance sponsor - regular executive dialogue.', '2026-08-19'),
  ('r2', 'c2', 'm1', 3, 'Executive sponsor relationship.', '2026-08-19'),
  ('r3', 'c1', 'm2', 3, 'Our main partner contact - weekly cadence.', '2026-08-19'),
  ('r4', 'c3', 'm2', 1, 'Occasional contact through Business Applications planning.', '2026-08-19'),
  ('r5', 'c1', 'm3', 3, 'Joint pipeline reviews on Azure & AI.', '2026-08-19'),
  ('r6', 'c4', 'm3', 3, 'Regular technical and commercial alignment.', '2026-08-19'),
  ('r7', 'c4', 'm4', 2, 'Ongoing dialogue on Azure opportunities.', '2026-08-19'),
  ('r8', 'c10', 'm4', 2, 'Works with us on architecture-led deals.', '2026-08-19'),
  ('r9', 'c7', 'm5', 1, 'Occasional contact on Data & AI pursuits.', '2026-08-19'),
  ('r10', 'c13', 'm5', 1, 'Met on a few joint pursuits.', '2026-08-19'),
  ('r11', 'c10', 'm6', 1, 'Introduced on a shared Azure opportunity.', '2026-08-19'),
  ('r12', 'c8', 'm6', -1, 'One-sided contact so far.', '2026-08-19'),
  ('r13', 'c13', 'm7', 2, 'Co-runs AI solution workshops with us.', '2026-08-19'),
  ('r14', 'c7', 'm7', 2, 'Regular contact on AI engagements.', '2026-08-19'),
  ('r15', 'c10', 'm8', 2, 'Joint architecture design sessions.', '2026-08-19'),
  ('r16', 'c4', 'm8', 0, 'Aware of each other, nothing active.', '2026-08-19'),
  ('r17', 'c10', 'm9', 2, 'Technical counterpart on Azure migrations.', '2026-08-19'),
  ('r18', 'c3', 'm11', 2, 'Ongoing Business Applications alignment.', '2026-08-19'),
  ('r19', 'c11', 'm11', 2, 'Regular dialogue on D365 and Power Platform.', '2026-08-19'),
  ('r20', 'c11', 'm12', 1, 'Occasional contact on Power Platform topics.', '2026-08-19'),
  ('r21', 'c3', 'm12', 1, 'Good rapport, no fixed cadence.', '2026-08-19'),
  ('r22', 'c11', 'm13', -1, 'Limited contact - hard to reach.', '2026-08-19'),
  ('r23', 'c8', 'm15', 1, 'Introduced at an SMC partner session.', '2026-08-19'),
  ('r24', 'c1', 'm15', 1, 'Occasional alliance contact.', '2026-08-19'),
  ('r25', 'c8', 'm16', 0, 'No real working relationship yet.', '2026-08-19'),
  ('r26', 'c4', 'm16', 0, 'Aware of each other only.', '2026-08-19'),
  ('r27', 'c8', 'm17', -2, 'Momentum lost after the last joint pursuit.', '2026-08-19'),
  ('r28', 'c7', 'm18', 3, 'First call on anything Fabric.', '2026-08-19'),
  ('r29', 'c13', 'm18', 3, 'Brings us into Fabric partner motions.', '2026-08-19'),
  ('r30', 'c1', 'm19', 1, 'Contact for funding and incentive questions.', '2026-08-19'),
  ('r31', 'c5', 'm23', -3, 'Repeated attempts at contact unanswered.', '2026-08-19'),
  ('dr1', 'c16', 'dm1', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr2', 'c18', 'dm2', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr3', 'c19', 'dm6', 3, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr4', 'c16', 'dm7', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr5', 'c16', 'm11', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr6', 'c16', 'm14', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr7', 'c19', 'm14', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr8', 'c19', 'dm8', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr9', 'c15', 'dm8', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr10', 'c24', 'dm11', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr11', 'c15', 'm2', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr12', 'c15', 'dm17', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr13', 'c18', 'dm18', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr14', 'c22', 'dm21', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr15', 'c21', 'dm22', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr16', 'c19', 'dm26', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr17', 'c19', 'dm28', 3, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr18', 'c16', 'm13', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr19', 'c19', 'm13', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr20', 'c20', 'm13', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr21', 'c24', 'dm37', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr22', 'c17', 'dm38', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr23', 'c26', 'dm42', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr24', 'c18', 'dm44', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr25', 'c24', 'dm47', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr26', 'c18', 'dm51', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr27', 'c23', 'dm55', 0, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr28', 'c19', 'dm59', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr29', 'c25', 'dm62', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr30', 'c15', 'm1', 2, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr31', 'c15', 'dm66', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr32', 'c15', 'm15', 3, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr33', 'c15', 'dm70', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr34', 'c20', 'dm72', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr35', 'c15', 'dm72', 1, 'From Thomas’ deck, 27 May 2026.', '2026-05-27'),
  ('dr36', 'c15', 'dm74', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr37', 'c16', 'dm76', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr38', 'c22', 'dm77', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27'),
  ('dr39', 'c16', 'dm78', 0, 'Owner named in the deck, no score given — recorded as 0.', '2026-05-27');

update ms_profiles set owner_id = o.owner from (values
  ('m1', 'c1'),
  ('m2', 'c1'),
  ('m3', 'c1'),
  ('m4', 'c4'),
  ('m5', 'c7'),
  ('m6', 'c10'),
  ('m7', 'c13'),
  ('m8', 'c10'),
  ('m9', 'c10'),
  ('m11', 'c3'),
  ('m12', 'c11'),
  ('m13', 'c16'),
  ('m14', 'c16'),
  ('m15', 'c15'),
  ('m16', 'c8'),
  ('m17', 'c8'),
  ('m18', 'c7'),
  ('m19', 'c1'),
  ('m23', 'c5'),
  ('dm1', 'c16'),
  ('dm2', 'c18'),
  ('dm6', 'c19'),
  ('dm7', 'c16'),
  ('dm8', 'c19'),
  ('dm11', 'c24'),
  ('dm17', 'c15'),
  ('dm18', 'c18'),
  ('dm21', 'c22'),
  ('dm22', 'c21'),
  ('dm26', 'c19'),
  ('dm28', 'c19'),
  ('dm37', 'c24'),
  ('dm38', 'c17'),
  ('dm42', 'c26'),
  ('dm44', 'c18'),
  ('dm47', 'c24'),
  ('dm51', 'c18'),
  ('dm55', 'c23'),
  ('dm59', 'c19'),
  ('dm62', 'c25'),
  ('dm66', 'c15'),
  ('dm70', 'c15'),
  ('dm72', 'c20'),
  ('dm74', 'c15'),
  ('dm76', 'c16'),
  ('dm77', 'c22'),
  ('dm78', 'c16')
) as o (id, owner) where ms_profiles.id = o.id;

insert into contacts (id, ms_profile_id, by_id, date) values
  ('ct1', 'm1', 'c1', current_date - 18),
  ('ct2', 'm1', 'c15', current_date - 79),
  ('ct3', 'm2', 'c1', current_date - 44),
  ('ct4', 'm2', 'c15', current_date - 105),
  ('ct5', 'm3', 'c1', current_date - 69),
  ('ct6', 'm5', 'c7', current_date - 120),
  ('ct7', 'm6', 'c10', current_date - 146),
  ('ct8', 'm7', 'c13', current_date - 15),
  ('ct9', 'm7', 'c7', current_date - 76),
  ('ct10', 'm9', 'c10', current_date - 66),
  ('ct11', 'm11', 'c3', current_date - 117),
  ('ct12', 'm13', 'c16', current_date - 12),
  ('ct13', 'm13', 'c20', current_date - 73),
  ('ct14', 'm14', 'c16', current_date - 38),
  ('ct15', 'm14', 'c19', current_date - 99),
  ('ct16', 'm15', 'c15', current_date - 63),
  ('ct17', 'm17', 'c8', current_date - 114),
  ('ct18', 'm18', 'c7', current_date - 167),
  ('ct19', 'm19', 'c1', current_date - 9),
  ('ct20', 'm19', 'c1', current_date - 70),
  ('ct21', 'm23', 'c5', current_date - 138),
  ('ct22', 'dm2', 'c18', current_date - 6),
  ('ct23', 'dm2', 'c18', current_date - 67),
  ('ct24', 'dm6', 'c19', current_date - 135),
  ('ct25', 'dm7', 'c16', current_date - 161),
  ('ct26', 'dm8', 'c19', current_date - 3),
  ('ct27', 'dm8', 'c15', current_date - 64),
  ('ct28', 'dm11', 'c24', current_date - 107),
  ('ct29', 'dm18', 'c18', current_date - 129),
  ('ct30', 'dm22', 'c21', current_date - 75),
  ('ct31', 'dm26', 'c19', current_date - 25),
  ('ct32', 'dm26', 'c19', current_date - 55),
  ('ct33', 'dm28', 'c19', current_date - 72),
  ('ct34', 'dm38', 'c17', current_date - 15),
  ('ct35', 'dm38', 'c17', current_date - 76),
  ('ct36', 'dm42', 'c26', current_date - 117),
  ('ct37', 'dm44', 'c18', current_date - 12),
  ('ct38', 'dm44', 'c18', current_date - 73),
  ('ct39', 'dm47', 'c24', current_date - 89),
  ('ct40', 'dm51', 'c18', current_date - 35),
  ('ct41', 'dm51', 'c18', current_date - 96),
  ('ct42', 'dm55', 'c23', current_date - 164),
  ('ct43', 'dm59', 'c19', current_date - 110),
  ('ct44', 'dm62', 'c25', current_date - 3),
  ('ct45', 'dm62', 'c25', current_date - 64),
  ('ct46', 'dm66', 'c15', current_date - 132),
  ('ct47', 'dm70', 'c15', current_date - 78),
  ('ct48', 'dm72', 'c20', current_date - 129),
  ('ct49', 'dm74', 'c15', current_date - 28),
  ('ct50', 'dm74', 'c15', current_date - 58),
  ('ct51', 'dm76', 'c16', current_date - 75),
  ('ct52', 'dm78', 'c16', current_date - 126);

commit;
